export const indicatorData = [
  {
    id: "1",
    dr: "0",
    targetName: "PSC Node Complete Rate",
    // targetName: "PSC节点任务完成率",
    targetDefine: null,
    formula: null,
    targetOwner: null,
    targetOwnerName: null,
    targetStatus: "10",
    targetLevel: "APP",
    targetType: "T",
    targetStatusDesc: "发布",
    targetLevelDesc: "应用级",
    targetTypeDesc: "T_计划",
    displayOrder: 1,
    status: 0,
    type: 0,
    userId: null,
    value: "38",
    targetNo: "01",
    ids: [],
  },
  {
    id: "2",
    dr: "0",
    targetName: "OP Task Complete Rate",
    targetDefine: null,
    formula: null,
    targetOwner: null,
    targetOwnerName: null,
    targetStatus: "10",
    targetLevel: "APP",
    targetType: "T",
    targetStatusDesc: "发布",
    targetLevelDesc: "应用级",
    targetTypeDesc: "T_计划",
    displayOrder: 2,
    status: 0,
    type: 0,
    userId: null,
    value: "65",
    targetNo: "02",
    ids: [],
  },
  {
    id: "3",
    dr: "0",
    targetName: "First Pass Yield Rate",
    targetDefine: null,
    formula: null,
    targetOwner: null,
    targetOwnerName: null,
    targetStatus: "10",
    targetLevel: "APP",
    targetType: "T",
    targetStatusDesc: "发布",
    targetLevelDesc: "应用级",
    targetTypeDesc: "T_计划",
    displayOrder: 3,
    status: 0,
    type: 0,
    userId: null,
    value: "90",
    targetNo: "03",
    ids: [],
  },
];
